# NumPy

[NumPy](https://docs.scipy.org/doc/numpy-1.10.0/index.html) is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. The ancestor of NumPy, Numeric, was originally created by Jim Hugunin with contributions from several other developers.

Use `import` to load NumPy.

In [2]:
import numpy as np

number = np.array(list(range(11, 17)))
print(type(number))

<class 'numpy.ndarray'>


Element-wise operations

In [7]:
print(number * 2)

print(number + number)

[22 24 26 28 30 32]
[22 24 26 28 30 32]


Subsetting

In [16]:
print(number[4])
print(number[1:3])
print(number[number > 13])

15
[12 13]
[14 15 16]


Subsetting using boolean operators

In [8]:
print(np.logical_and(number > 13, number < 15))
print(np.logical_or(number == 13, number > 15))

print(number[np.logical_or(number == 13, number > 15)])

[False False False  True False False]
[False False  True False False  True]
[13 16]


Coercion

In [15]:
test = np.array([True, "string", 1])

# all types coerced into type string
print(test)
print(type(test[0]))

# coerced into intergers
test2 = np.array([True, False, 1])
print(test2)
print(type(test2[0]))

['True' 'string' '1']
<class 'numpy.str_'>
[1 0 1]
<class 'numpy.int64'>


N-dimensional arrays

In [9]:
test3 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(test3)
print(type(test3))
print(test3[0,:])
print(test3[:,1])
print(test3.shape)
print(test3[1][1])
print(test3[1, 1])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[1 2 3]
[2 5]
(2, 3)
5
5


Looping over n-dimensional arrays

In [10]:
for x in np.nditer(test3):
    print(x)

1
2
3
4
5
6


Basic statistics using the famous iris dataset

In [42]:
from sklearn import datasets
iris = datasets.load_iris()
print(type(iris))

# view first few rows
print(iris.data[0:6,])

# print dimension
print(iris.data.shape)

# type of column
print(type(iris.data[:,0]))

print(np.mean(iris.data[:, 0]))
print(np.median(iris.data[:,0]))
print(np.sum(iris.data[:,0]))
print(np.corrcoef(iris.data[:,0], iris.data[:,1]))

<class 'sklearn.utils.Bunch'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]
(150, 4)
<class 'numpy.ndarray'>
5.843333333333334
5.8
876.5
[[ 1.         -0.10936925]
 [-0.10936925  1.        ]]


Random numbers using [numpy.random](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

In [7]:
np.random.seed(1984)
print(np.random.rand())

# simulate a die
print(np.random.randint(1,7))

0.00875572949604042
4
