# Programming with Python

[Programming with Python course](https://swcarpentry.github.io/python-novice-inflammation/) by Software Carpentry.

## Python Fundamentals

* Basic data types in Python include integers, strings, and floating-point numbers.
* Use `variable = value` to assign a value to a variable in order to record it in memory.
* Variables are created on demand whenever a value is assigned to them.
* Use `print(something)` to display the value of `something`.
* Built-in functions are always available to use.

## Analysing Patient Data

Load `NumPy` and load `inflammation-01.csv`.

In [2]:
import numpy as np
data = np.loadtxt(fname = '../data/swc/inflammation-01.csv', delimiter=',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


Data type using `type()`.

In [3]:
print(type(data))

<class 'numpy.ndarray'>


The `type()` function will only tell you that a variable is a `NumPy` array but not the type of values stored in the array.

In [4]:
print(data.dtype)

float64


`data.shape` is an attribute of `data` that describes dimensions of `data`.

In [6]:
print(data.shape)

(60, 40)


Get first value (cell in first row and first column).

In [8]:
print(data[0, 0])

0.0
